name: angular_quill
description: Angular dart component for the Quill rich text editor. Quill is a free, open source WYSIWYG editor built for the modern web.
version: 0.1.3
homepage: https://github.com/adamlofts/angular_quill

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: '>=5.0.0 <7.0.0'
  angular_forms: '>=2.0.0 <=2.1.4'
  js: ^0.6.1+1

dev_dependencies:
